version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: lahittm/todo-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: lahittm/todo-backend:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - db


volumes:
  pgdata:
