name: Nightly E2E Tests

on:
  schedule:
    - cron: '0 22 * * *' # Tous les jours à 22h

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        run: docker-compose up -d

      - name: Wait for Services
        run: sleep 15 # ou script de healthcheck

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e
